service: dns-sandbox
provider:
  name: aws
  runtime: nodejs12.x
  stage: "${opt:stage, 'stg'}"
  region: "${opt:region, 'ap-southeast-1'}"
  memorySize: 256
  tracing:
    lambda: true
    apiGateway: true
  logs:
    restApi: true

functions:
  status:
    description: "I have no idea how to not put a definition yet"
    handler: index.create
  create:
    description: "Checks the validity of the certificate against the 4 checks."
    handler: index.create
  clean:
    description: "Checks the validity of the certificate against the 4 checks."
    handler: index.clean

stepFunctions:
  stateMachines:
    status:
      events:
        - http:
            path: status
            method: POST
            action: DescribeExecution
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource:
              Fn::GetAtt: [status, Arn]
            End: true
    records:
      events:
        - http:
            path: /
            method: POST
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: CreateRecord
        States:
          CreateRecord:
            Type: Task
            Resource:
              Fn::GetAtt: [create, Arn]
            Next: Wait
          Wait:
            Type: Wait
            Seconds: 3600
            Next: DeleteRecord
          DeleteRecord:
            Type: Task
            Resource:
              Fn::GetAtt: [clean, Arn]
            End: true

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-plugin-typescript
